"""Canonical, provider-neutral Denali domain types."""

from denali.domain.findings import (
    AffectedResource,
    EvaluationResult,
    FindingAssertion,
    FindingBatch,
    FindingSeverity,
    FindingState,
)
from denali.domain.inventory import (
    AssertionType,
    AssetAssertion,
    AssetKind,
    AssetRef,
    ConnectorCapabilities,
    Coverage,
    CoverageState,
    Evidence,
    GovernanceStatus,
    InventoryBatch,
    LifecycleState,
    RelationshipAssertion,
    RelationshipCategory,
    RelationshipKind,
)
from denali.domain.issues import (
    CorrelationAsset,
    CorrelationFinding,
    CorrelationRelationship,
    CorrelationSnapshot,
    IssueCandidate,
    IssueEvaluation,
    IssueFindingLink,
    IssuePathEdge,
    IssuePathNode,
    IssueState,
)

__all__ = [
    "AffectedResource",
    "AssertionType",
    "AssetAssertion",
    "AssetKind",
    "AssetRef",
    "ConnectorCapabilities",
    "CorrelationAsset",
    "CorrelationFinding",
    "CorrelationRelationship",
    "CorrelationSnapshot",
    "Coverage",
    "CoverageState",
    "Evidence",
    "EvaluationResult",
    "FindingAssertion",
    "FindingBatch",
    "FindingSeverity",
    "FindingState",
    "GovernanceStatus",
    "InventoryBatch",
    "IssueCandidate",
    "IssueEvaluation",
    "IssueFindingLink",
    "IssuePathEdge",
    "IssuePathNode",
    "IssueState",
    "LifecycleState",
    "RelationshipAssertion",
    "RelationshipCategory",
    "RelationshipKind",
]
